# TensorFlow Computation Graphs

In [2]:
import tensorflow as tf

In [3]:
## TF v1.x style
g = tf.Graph() #initialise the graph

with g.as_default(): # add nodes to graph
    a = tf.constant(1, name='a')
    b = tf.constant(2, name='b')
    c = tf.constant(3, name='c')
    z = 2*(a-b) + c

In [4]:
## TF v1.x style
with tf.compat.v1.Session(graph=g) as sess:
    print ('Result: z =', sess.run(z))

2022-01-31 16:11:26.942629: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2022-01-31 16:11:27.015870: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-01-31 16:11:27.016275: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:01:00.0
2022-01-31 16:11:27.016310: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-01-31 16:11:27.016680: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000

Result: z = 1


In [5]:
## TF v2 style
a = tf.constant(1, name='a')
b = tf.constant(2, name='b')
c = tf.constant(3, name='c')
z = 2*(a-b)+c
tf.print('Result: z= ', z)

Result: z=  1


2022-01-31 16:13:01.938072: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-01-31 16:13:01.938351: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:01:00.0
2022-01-31 16:13:01.938400: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-01-31 16:13:01.938762: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:02:00.0
2022-01-31 16:13:01.938785: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libc

In [6]:
## TF-v1.x style
g = tf.Graph()
with g.as_default():
    a = tf.compat.v1.placeholder(shape=None, dtype=tf.int32, name='tf_a')
    b = tf.compat.v1.placeholder(shape=None, dtype=tf.int32, name='tf_b')
    c = tf.compat.v1.placeholder(shape=None, dtype=tf.int32, name='tf_c')
    z = 2*(a-b)+c

In [8]:
with tf.compat.v1.Session(graph=g) as sess:
    feed_dict={a:1, b:2, c:3} # dictionary
    print('Result: z=', sess.run(z, feed_dict=feed_dict))

Result: z= 1


2022-01-31 16:17:19.814097: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-01-31 16:17:19.814541: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:01:00.0
2022-01-31 16:17:19.814629: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-01-31 16:17:19.815143: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:02:00.0
2022-01-31 16:17:19.815217: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libc

In [9]:
## TF-v2 style
def compute_z(a,b,c):
    r1 = tf.subtract(a,b)
    r2 = tf.multiply(2, r1)
    z = tf.add(r2, c)
    return z

In [10]:
tf.print('Scalar Inputs:', compute_z(1,2,3))

Scalar Inputs: 1


## Improving computational performance with function decorators

In [11]:
@tf.function
def compute_z(a,b,c):
    r1 = tf.subtract(a,b)
    r2 = tf.multiply(2, r1)
    z = tf.add(r2, c)
    return z

In [12]:
tf.print('Scalar Inputs:', compute_z(1,2,3))

Scalar Inputs: 1


In [13]:
tf.print('Rank 1 Inputs:', compute_z([1],[2],[3]))

Rank 1 Inputs: [1]


In [14]:
@tf.function(input_signature=(tf.TensorSpec(shape=[None], dtype=tf.int32),
                              tf.TensorSpec(shape=[None], dtype=tf.int32),
                              tf.TensorSpec(shape=[None], dtype=tf.int32)))
def compute_z(a,b,c):
    r1 = tf.subtract(a,b)
    r2 = tf.multiply(2, r1)
    z = tf.add(r2, c)
    return z

In [15]:
tf.print('Rank 1 Inputs:', compute_z([1],[2],[3]))

Rank 1 Inputs: [1]


In [17]:
#tf.print('Rank 0 Inputs:', compute_z(1,2,3))
### will result in error - specified input signature is tensor of rank 1

In [18]:
a = tf.Variable(initial_value=3.14, name='var_a')
print(a)

<tf.Variable 'var_a:0' shape=() dtype=float32, numpy=3.14>


In [19]:
b = tf.Variable(initial_value=[1, 2, 3], name='var_b')
print(b)

<tf.Variable 'var_b:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>


In [20]:
c = tf.Variable(initial_value=[True, False], dtype=tf.bool)
print(c)

<tf.Variable 'Variable:0' shape=(2,) dtype=bool, numpy=array([ True, False])>


In [21]:
d = tf.Variable(initial_value=['abc'], dtype=tf.string)
print(d)

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'abc'], dtype=object)>


In [22]:
w = tf.Variable([1,2,3], trainable=False)
print(w.trainable)

False


In [23]:
print(w.assign([3, 1, 4], read_value=True))

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([3, 1, 4], dtype=int32)>


In [24]:
w.assign_add([2, -1, 2], read_value=False)
print(w.value())

tf.Tensor([5 0 6], shape=(3,), dtype=int32)


In [25]:
tf.random.set_seed(1)
init = tf.keras.initializers.GlorotNormal()
tf.print(init(shape=(3,)))

[-0.722795904 1.01456821 0.251808226]


In [26]:
v = tf.Variable(init(shape=(2,3)))
tf.print(v)

[[0.28982234 -0.782292783 -0.0453658961]
 [0.960991383 -0.120003454 0.708528221]]


In [27]:
class MyModule(tf.Module):
    def __init__(self):
        init = tf.keras.initializers.GlorotNormal()
        self.w1 = tf.Variable(init(shape=(2,3)),trainable=True)
        self.w2 = tf.Variable(init(shape=(1,2)),trainable=False)

In [28]:
m = MyModule()
print('All module variables:', [v.shape for v in m.variables])

All module variables: [TensorShape([2, 3]), TensorShape([1, 2])]


2022-01-31 17:27:53.466599: W tensorflow/python/util/util.cc:299] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.


In [29]:
print('Trainable variable:', [v.shape for v in m.trainable_variables])

Trainable variable: [TensorShape([2, 3])]


In [30]:
w = tf.Variable(tf.random.uniform((3,3)))
@tf.function
def compute_z(x):
    return tf.matmul(w,x)

In [32]:
x = tf.constant([[1],[2],[3]], dtype=tf.float32)
tf.print(compute_z(x))

[[1.20935762]
 [3.89828062]
 [1.65398622]]


2022-01-31 17:33:05.395684: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
