# TensorFlow Computation Graphs

In [1]:
import tensorflow as tf

In [2]:
## TF v1.x style
g = tf.Graph() #initialise the graph

with g.as_default(): # add nodes to graph
    a = tf.constant(1, name='a')
    b = tf.constant(2, name='b')
    c = tf.constant(3, name='c')
    z = 2*(a-b) + c

In [3]:
## TF v1.x style
with tf.compat.v1.Session(graph=g) as sess:
    print ('Result: z =', sess.run(z))

2022-02-01 11:02:41.607187: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2022-02-01 11:02:41.691280: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-01 11:02:41.691966: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:01:00.0
2022-02-01 11:02:41.692037: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-01 11:02:41.692692: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000

Result: z = 1


In [4]:
## TF v2 style
a = tf.constant(1, name='a')
b = tf.constant(2, name='b')
c = tf.constant(3, name='c')
z = 2*(a-b)+c
tf.print('Result: z= ', z)

Result: z=  1


2022-02-01 11:02:41.962005: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-01 11:02:41.962250: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:01:00.0
2022-02-01 11:02:41.962301: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-01 11:02:41.962638: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:02:00.0
2022-02-01 11:02:41.962660: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libc

In [5]:
## TF-v1.x style
g = tf.Graph()
with g.as_default():
    a = tf.compat.v1.placeholder(shape=None, dtype=tf.int32, name='tf_a')
    b = tf.compat.v1.placeholder(shape=None, dtype=tf.int32, name='tf_b')
    c = tf.compat.v1.placeholder(shape=None, dtype=tf.int32, name='tf_c')
    z = 2*(a-b)+c

In [6]:
with tf.compat.v1.Session(graph=g) as sess:
    feed_dict={a:1, b:2, c:3} # dictionary
    print('Result: z=', sess.run(z, feed_dict=feed_dict))

Result: z= 1


2022-02-01 11:02:41.993684: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-01 11:02:41.993952: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:01:00.0
2022-02-01 11:02:41.994012: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-01 11:02:41.994444: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:02:00.0
2022-02-01 11:02:41.994487: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libc

In [7]:
## TF-v2 style
def compute_z(a,b,c):
    r1 = tf.subtract(a,b)
    r2 = tf.multiply(2, r1)
    z = tf.add(r2, c)
    return z

In [8]:
tf.print('Scalar Inputs:', compute_z(1,2,3))

Scalar Inputs: 1


## Improving computational performance with function decorators

In [9]:
@tf.function
def compute_z(a,b,c):
    r1 = tf.subtract(a,b)
    r2 = tf.multiply(2, r1)
    z = tf.add(r2, c)
    return z

In [10]:
tf.print('Scalar Inputs:', compute_z(1,2,3))

Scalar Inputs: 1


In [11]:
tf.print('Rank 1 Inputs:', compute_z([1],[2],[3]))

Rank 1 Inputs: [1]


In [12]:
@tf.function(input_signature=(tf.TensorSpec(shape=[None], dtype=tf.int32),
                              tf.TensorSpec(shape=[None], dtype=tf.int32),
                              tf.TensorSpec(shape=[None], dtype=tf.int32)))
def compute_z(a,b,c):
    r1 = tf.subtract(a,b)
    r2 = tf.multiply(2, r1)
    z = tf.add(r2, c)
    return z

In [13]:
tf.print('Rank 1 Inputs:', compute_z([1],[2],[3]))

Rank 1 Inputs: [1]


In [14]:
#tf.print('Rank 0 Inputs:', compute_z(1,2,3))
### will result in error - specified input signature is tensor of rank 1

In [15]:
a = tf.Variable(initial_value=3.14, name='var_a')
print(a)

<tf.Variable 'var_a:0' shape=() dtype=float32, numpy=3.14>


In [16]:
b = tf.Variable(initial_value=[1, 2, 3], name='var_b')
print(b)

<tf.Variable 'var_b:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>


In [17]:
c = tf.Variable(initial_value=[True, False], dtype=tf.bool)
print(c)

<tf.Variable 'Variable:0' shape=(2,) dtype=bool, numpy=array([ True, False])>


In [18]:
d = tf.Variable(initial_value=['abc'], dtype=tf.string)
print(d)

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'abc'], dtype=object)>


In [19]:
w = tf.Variable([1,2,3], trainable=False)
print(w.trainable)

False


In [20]:
print(w.assign([3, 1, 4], read_value=True))

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([3, 1, 4], dtype=int32)>


In [21]:
w.assign_add([2, -1, 2], read_value=False)
print(w.value())

tf.Tensor([5 0 6], shape=(3,), dtype=int32)


In [22]:
tf.random.set_seed(1)
init = tf.keras.initializers.GlorotNormal()
tf.print(init(shape=(3,)))

[-0.722795904 1.01456821 0.251808226]


In [23]:
v = tf.Variable(init(shape=(2,3)))
tf.print(v)

[[0.28982234 -0.782292783 -0.0453658961]
 [0.960991383 -0.120003454 0.708528221]]


In [24]:
class MyModule(tf.Module):
    def __init__(self):
        init = tf.keras.initializers.GlorotNormal()
        self.w1 = tf.Variable(init(shape=(2,3)),trainable=True)
        self.w2 = tf.Variable(init(shape=(1,2)),trainable=False)

In [25]:
m = MyModule()
print('All module variables:', [v.shape for v in m.variables])

All module variables: [TensorShape([2, 3]), TensorShape([1, 2])]


2022-02-01 11:02:42.592695: W tensorflow/python/util/util.cc:299] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.


In [26]:
print('Trainable variable:', [v.shape for v in m.trainable_variables])

Trainable variable: [TensorShape([2, 3])]


In [27]:
w = tf.Variable(tf.random.uniform((3,3)))
@tf.function
def compute_z(x):
    return tf.matmul(w,x)

In [28]:
x = tf.constant([[1],[2],[3]], dtype=tf.float32)
tf.print(compute_z(x))

[[1.20935762]
 [3.89828062]
 [1.65398622]]


2022-02-01 11:02:42.644421: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0


# Computing gradients via automatic differentiation and GradientTape

## Gradients of Trainable variables i.e. weights & biases

In [29]:
w = tf.Variable(1.0)
b = tf.Variable(0.5)
print(w.trainable, b.trainable)

True True


In [30]:
x = tf.convert_to_tensor([1.4])
y = tf.convert_to_tensor([2.1])
with tf.GradientTape() as tape:
    z = tf.add(tf.multiply(w,x), b)
    loss = tf.reduce_sum(tf.square(y-z))

In [31]:
dloss_dw = tape.gradient(loss, w) # dL, dw
tf.print('dL/dw:', dloss_dw)

dL/dw: -0.559999764


In [32]:
# verifying the computed gradient
tf.print(2*x*(w*x+b-y))

[-0.559999764]


## Gradients of Non-Trainable variables i.e. inputs

In [34]:
with tf.GradientTape() as tape:
    tape.watch(x)
    z = tf.add(tf.multiply(w,x),b)
    loss = tf.reduce_sum(tf.square(y-z))

In [35]:
dloss_dx = tape.gradient(loss, x) # dL, dx

In [36]:
tf.print('dL/dx:',dloss_dx) 

dL/dx: [-0.399999857]


## Multiple gradient computations

In [37]:
with tf.GradientTape(persistent=True) as tape: #persistence!!!!
    z = tf.add(tf.multiply(w,x),b)
    loss = tf.reduce_sum(tf.square(y-z))

In [38]:
dloss_dw = tape.gradient(loss, w)
tf.print('dL/dw:', dloss_dw)

dL/dw: -0.559999764


In [39]:
dloss_db = tape.gradient(loss, b)
tf.print('dL/db:', dloss_db)

dL/db: -0.399999857


In [40]:
optimizer = tf.keras.optimizers.SGD()
optimizer.apply_gradients(zip([dloss_dw, dloss_db], [w,b]))

<tf.Variable 'UnreadVariable' shape=() dtype=int64, numpy=1>

In [43]:
tf.print('Updated weight:', w)

Updated weight: 1.0056


In [44]:
tf.print('Updated bias:', b)

Updated bias: 0.504


# Simplifying implementations of common architectures via the Keras API

In [45]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(units=16, activation='relu'))
model.add(tf.keras.layers.Dense(units=32, activation='relu'))
## late variable creation
model.build(input_shape=(None, 4))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                multiple                  80        
_________________________________________________________________
dense_1 (Dense)              multiple                  544       
Total params: 624
Trainable params: 624
Non-trainable params: 0
_________________________________________________________________


In [46]:
## printing variables of the model
for v in model.variables:
    print('{:20s}'.format(v.name), v.trainable, v.shape)

dense/kernel:0       True (4, 16)
dense/bias:0         True (16,)
dense_1/kernel:0     True (16, 32)
dense_1/bias:0       True (32,)


In [49]:
model = tf.keras.Sequential()
model.add(
    tf.keras.layers.Dense(
        units = 16,
        activation = tf.keras.activations.relu,
        kernel_initializer = tf.keras.initializers.glorot_uniform(),
        bias_initializer = tf.keras.initializers.Constant(2.0)
    ))

model.add(
    tf.keras.layers.Dense(
        units=32,
        activation=tf.keras.activations.sigmoid,
        kernel_regularizer=tf.keras.regularizers.l1
    )
)

In [50]:
model.compile(
    optimizer = tf.keras.optimizers.SGD(learning_rate=0.001),
    loss = tf.keras.losses.BinaryCrossentropy(),
    metrics = [tf.keras.metrics.Accuracy(),
               tf.keras.metrics.Precision(),
               tf.keras.metrics.Recall()]
)